version: '2.1'

services:
  data:
    image: oroinc/data:latest
    volumes:
      - "${BUILD_DIR:-.}/.composer/cache:/usr/local/composer/cache"
      - "${BUILD_DIR:-.}/.composer/auth:/usr/local/composer/auth"
      - "${ORO_APP}:/var/www/html/application"
      - "${ORO_APP}/../../package:/var/www/package"

  data-cache-named:
    image: oroinc/data-cache:latest
    volumes:
      - "cache:/var/www/html/application/var/cache/"

  data-cache-anonymous:
    image: oroinc/data-cache:latest
    volumes:
      - "/var/www/html/application/var/cache/"
