version: '2.1'

services:
  consumer:
    extends:
      file: consumer.yml
      service: consumer${ORO_PHP:-7.1}
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN
      - SYMFONY_ENV
      - SYMFONY_DEBUG
      - XDEBUG_ENABLED

  consumer5.6:
    image: oroinc/consumer:5.6-xenial

  consumer7.0:
    image: oroinc/consumer:7.0-xenial

  consumer7.1:
    image: oroinc/consumer:7.1-xenial
