version: '2.1'

services:
  cron:
    extends:
      file: cron.yml
      service: cron${ORO_PHP:-7.1}
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN
      - SYMFONY_ENV
      - SYMFONY_DEBUG
      - XDEBUG_ENABLED

  cron5.6:
    image: oroinc/cron:5.6-xenial

  cron7.0:
    image: oroinc/cron:7.0-xenial

  cron7.1:
    image: oroinc/cron:7.1-xenial
